export const SET_CRYPTO_PRICES = 'SET_CRYPTO_PRICES';
export const GET_CRYPTO_PRICES_FAILED = 'GET_CRYPTO_PRICES_FAILED';
export const GET_CRYPTO_PORTFOLIO_FAILED = 'GET_CRYPTO_PORTFOLIO_FAILED';
export const UPDATE_CRYPTO_PORTFOLIO = 'UPDATE_CRYPTO_PORTFOLIO';
export const UPDATE_CRYPTO_PORTFOLIO_FAILED = 'UPDATE_CRYPTO_PORTFOLIO_FAILED';
export const GET_CRYPTO_START = 'GET_CRYPTO_START';
export const SET_CRYPTO_PORTFOLIO = 'SET_CRYPTO_PORTFOLIO';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';

export const SET_STOCK_PRICES = 'SET_STOCK_PRICES';
export const GET_STOCK_PRICES_FAILED = 'GET_STOCK_PRICES_FAILED';
export const GET_STOCK_PORTFOLIO_FAILED = 'GET_STOCK_PORTFOLIO_FAILED';
export const UPDATE_STOCK_PORTFOLIO = 'UPDATE_STOCK_PORTFOLIO';
export const UPDATE_STOCK_PORTFOLIO_FAILED = 'UPDATE_STOCK_PORTFOLIO_FAILED';
export const GET_STOCK_START = 'GET_STOCK_START';
export const SET_STOCK_PORTFOLIO = 'SET_STOCK_PORTFOLIO';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERROR = 'CLEAR_ERROR';
